# Generated by Django 2.0 on 2022-02-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_settings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('value', models.BooleanField(verbose_name=True)),
            ],
            options={
                'db_table': 'admin_settings',
            },
        ),
    ]
