# Generated by Django 2.0 on 2022-02-23 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='another_test_settings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('value', models.BooleanField(verbose_name=True)),
                ('value2', models.BooleanField(verbose_name=True)),
            ],
            options={
                'db_table': 'another_test_settings',
            },
        ),
        migrations.CreateModel(
            name='test_settings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('value', models.BooleanField(verbose_name=True)),
            ],
            options={
                'db_table': 'test_settings',
            },
        ),
        migrations.CreateModel(
            name='user_settings',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True)),
                ('show_alerts', models.BooleanField(verbose_name=True)),
            ],
        ),
    ]
