# Generated by Django 2.2.27 on 2022-02-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220223_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent_alerts',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
